export const FILE_COMPLAINT_SUCCESS = "FILE_COMPLAINT_SUCCESS";
export const FILE_COMPLAINT_FAILED = "FILE_COMPLAINT_FAILED";
export const GET_COMPLAINT_SUCCESS = "GET_COMPLAINT_SUCCESS";
export const GET_COMPLAINT_FAILED = "GET_COMPLAINT_FAILED";
